version: "3.1"
services:
  db:
    image: mariadb
    container_name: db-container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=d3v3lopm3nt
      - MYSQL_DATABASE=viloveul_cms
      - MYSQL_USER=viloveul
      - MYSQL_PASSWORD=viloveul

  queue:
    image: rabbitmq:3.7-alpine
    container_name: queue-container
    restart: always

  restapi-viloveul-cms:
    image: fajrulaz/viloveul-cms-restapi
    container_name: viloveul-cms-restapi
    restart: always
    volumes:
      - ./private.pem:/viloveul/var/private.pem
      - ./public.pem:/viloveul/var/public.pem
      - ./vendor:/viloveul/vendor
    ports:
      - "19911:19911"
    environment:
      - VILOVEUL_AUTH_PASSPHRASE=viloveul
      - VILOVEUL_CACHE_ADAPTER=apcu
      - VILOVEUL_DB_HOST=db
      - VILOVEUL_BROKER_DSN=amqp://queue:5672//
      - ADMIN_EMAIL=me@viloveul.com
      - ADMIN_PASSWORD=dordordor
    depends_on:
      - db
      - queue
    links:
      - db
      - queue

  dashboard-viloveul-cms:
    image: fajrulaz/viloveul-cms-dashboard
    container_name: viloveul-cms-dashboard
    restart: always
    volumes:
      - ./node_modules:/viloveul/node_modules
    ports:
      - "19912:19912"
    depends_on:
      - restapi-viloveul-cms

  consumer-viloveul-cms:
    image: fajrulaz/viloveul-cms-consumer
    container_name: viloveul-cms-consumer
    restart: always
    volumes:
      - ./node_modules:/viloveul/node_modules
    ports:
      - "19913:19913"
    depends_on:
      - restapi-viloveul-cms
      - dashboard-viloveul-cms